pipeline:
  - name: "tokenizer_whitespace"
  - name: "intent_entity_featurizer_regex"
  - name: "ner_crf" 
    BILOU_flag: true 
  - name: ner_synonyms
  - name: intent_featurizer_count_vectors
    token_pattern: (?u)\b\w+\b
  - name: "classifiers.intent_classifier_tensorflow.EmbeddingIntentClassifier"
    dimensions:
    - number
